### ISSUE TITLE
General help

### ISSUE THREAD

**Issue by StevenRKM** [sonicretro/s1disasm#12]
Hi, I'm a beginner at this, and first want to say I love the work!
But when opening this up in SonLVL I seem to be getting some weird red, yellow and green blocks.
As you see in the screenshot, these are the flowers and the top of the waterfall. Are they missing? Or is it because (I think) they are animated in the game?
And how can I display them better for export to PNG?

There's also a yellow line around the looping which is a bit weird.

Thanks

![assets_sonic](https://cloud.githubusercontent.com/assets/624306/15443567/a22fabb0-1ee9-11e6-8467-2a886b3db64d.PNG)

**Comment by Clownacy** [comment]
Yes, those are placeholder tiles. IIRC, the tiles they represent are stored uncompressed, separately from the normal Nemesis-compressed art file, so there's no easy way to make them display. The outline you see around the loop-de-loop indicates that it is a loop-enabled loop chunk.

I suggest further SonLVL queries be directed to the SonLVL repo.

**Comment by StevenRKM** [comment]
Thanks for the information!
