### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by TheRealPiggyWiggy** [sonicretro/s1disasm#13]
How do i spindash?

**Comment by TheRealPiggyWiggy** [comment]
I meant how to code a spindash

**Comment by MainMemory** [comment]
This is not a help desk for Sonic hacking. Try SSRG or the Sonic Retro wiki.

**Comment by TheRealPiggyWiggy** [comment]
oh

**Comment by TheRealPiggyWiggy** [comment]
When i was coding the spin dash when i tried to compile it, it saved as a 1
kilobyte file!

**Comment by TheRealPiggyWiggy** [comment]
nvm thats fixed

**Comment by MainMemory** [comment]
Again, this is not a help desk. We don't care about your Sonic hack. Go somewhere else.
