### ISSUE TITLE
[AS] Include AS license (and where to find AS)

### ISSUE THREAD

**Issue by SoniEx2** [sonicretro/s1disasm#15]
AS is GPLv2-licensed. It took me forever to find the source. You should include the AS license in `AS/`, and a README saying where to get the AS source from.

(~~In the mean time I'll get back to seeing if I can get this thing to build on a Raspberry Pi 3.~~ Edit: It works!)

**Comment by Clownacy** [comment]
Heh, so finally somebody but me noticed. This is an issue in s2disasm and skdisasm as well. I'm not the most well-versed in GPL, but I was never sure if a simple readme saying where to find the source was good enough. Stallman sure as heck disagrees.

Anyhow, I'm kind of suspicious that s2disasm's copy of AS is modified. If I build my own copy of Build 89, I get a bunch of warning prints every time I build the ROM. The preassembled one doesn't have that issue.

**Comment by SoniEx2** [comment]
You do need to include the full license, I know that much.

**Comment by Clownacy** [comment]
Hmm. The Kosinski compressors used by s1p2bin are under a license as well: LGPL. The KENS one already has its license, but FW-KENSC doesn't.
