### ISSUE TITLE
Incorrect block drawing label names

### ISSUE THREAD

**Issue by TheStoneBanana** [sonicretro/s1disasm#16]
A handful of label names in relation to block drawing functions are misleading/incorrect.
For instance, the subroutine on [line 4,870](https://github.com/sonicretro/s1disasm/blob/master/sonic.asm#L4870) labelled as "DrawBlocks" actually retrieves block mapping data based upon the camera's coordinates, and given horizontal and vertical positions relative to the screen. The actual function for drawing a block, found on [line 4,783](https://github.com/sonicretro/s1disasm/blob/master/sonic.asm#L4783), is labelled as "DrawTiles" (which is _technically_ correct, but doesn't quite fit for what the subroutine is actually doing).

**Comment by MainMemory** [comment]
Perhaps you should improve the labels yourself and submit a pull request.

**Comment by TheStoneBanana** [comment]
Oh I apologize, I'm not quite Git savvy and thought this would be the place to bring it up. I'll take your suggestion and do so when I can. Sorry.

**Comment by MainMemory** [comment]
This is the place to bring up such things, but if you submit a PR, it saves us the trouble of trying to guess at exactly what you want. Or at the very least, you could have given suggestions for what to change the labels to.

**Comment by Clownacy** [comment]
The level drawer's always been one of those areas I could never figure out. I guess those bad labels are partly to blame. But thanks, I guess I'll give it one last shot.

**Comment by TheStoneBanana** [comment]
I'm going to close this now, as I've made the pull request.
Thank you for helping me out MainMemory, and once again, I apologize for going about this the wrong way.
