### ISSUE TITLE
Make REV01 the default?

### ISSUE THREAD

**Issue by Clownacy** [sonicretro/s1disasm#21]
I don't really see a reason to make REV00 the default when it's so much more inferior. If anything, I think building an _older_ version of the game should be the option that's hidden away behind an assembler flag.

I might bring up a similar issue for S2's REV02 later, when I split its bugs into a 'Sonic Classics' build.

REVXB is a debatable build (and really hackishly done), so I don't think I'll ever suggest making that the default.

I think there might need to be some usability tweaks to make this really work though, like changing the SonLVL files so REV01 gets SonLVL.ini, and REV00 gets SonLVL.rev00.ini, to prevent newbs from using the wrong one.

**Comment by flamewing** [comment]
For what is worth, I agree with making rev01 the default.
