### ISSUE TITLE
No way to view level chunks

### ISSUE THREAD

**Issue by etha-tren** [sonicretro/s1disasm#26]
I cant download a file with all the chunks for a level, I would really love it if you could show me a way to get a png or something like that for all the chunks (websites show objects but not level chunks). More important than you think please help as i need to use this for my Round Table Assessment

**Comment by MainMemory** [comment]
This isn't a valid issue, it's not a problem with or suggestion for the disassembly, this isn't a place to ask for help with your projects. In the future, please go to [Sonic Retro](https://forums.sonicretro.org/) or [SSRG](http://sonicresearch.org/community/index.php) for help.

That said, [SonLVL](http://forums.sonicretro.org/index.php?showtopic=24378) can help you to get images of the chunks in a level.
