### ISSUE TITLE
Project Sonic 1 Two-Eight misplaced ring

### ISSUE THREAD

**Issue by Clownacy** [sonicretro/s1disasm#28]
Apparently the Two-Eight branch misplaced a ring above the loop in GHZ Act 2. This was probably inherited from the original Two-Eight project. There might be other mistakes like this, so maybe a tool to analyse all the differences would be nice.

**Comment by MainMemory** [comment]
ObjectLayoutMerge?

**Comment by Clownacy** [comment]
Fixed by 8350230c8edfa64edb870c7b2f409b57e457fb53.
