### ISSUE TITLE
You forgot something.

### ISSUE THREAD

**Issue by Nacob** [sonicretro/s1disasm#33]
You forgot to put "Sonic pattern load cues.asm" in the "_inc" folder.

**Comment by MainMemory** [comment]
What?

**Comment by Nacob** [comment]
I mean you forgot to put "Sonic dynamic pattern load cues.asm" in the "_inc" folder.

**Comment by flamewing** [comment]
There isn't not there ever was such a file, so how could it have been forgotten?

Perhaps you mean "_incObj/Sonic LoadGfx.asm" instead?

**Comment by flamewing** [comment]
Or maybe you are confusing this with the S&K disassembly, which does have a "Sonic pattern load cues.asm", but it is in another location.

**Comment by MainMemory** [comment]
The equivalent file in this disassembly is "_maps/Sonic - Dynamic Gfx Script.asm".
