### ISSUE TITLE
how to build on *nix

### ISSUE THREAD

**Issue by dvogit** [sonicretro/s1disasm#48]
How can I build this on my FreeBSD 12.1-RELEASE box? I have 2 assemblers that might be able to handle it:

* [`vasm`](http://sun.hasenbraten.de/vasm/)
* [`asl`](http://john.ccac.rwth-aachen.de:8000/as/)

But I don't exactly which one to use and how to build it properly, so how would I go about building this on *nix?

**Comment by Clownacy** [comment]
Use the AS branch - that one targets `asl`. You might have to compile [s1p2bin](https://github.com/sonicretro/s1disasm/tree/AS/AS) for you platform, and extend [build.py](https://github.com/sonicretro/s1disasm/blob/AS/build.py) to support the BSDs.

**Comment by dvogit** [comment]
perfect, built correctly
