### ISSUE TITLE
Outdated AS branch build tools

### ISSUE THREAD

**Issue by Clownacy** [sonicretro/s1disasm#6]
While I can keep the Windows 'exe's up to date, I don't think I can do anything for OS X and Linux. OS X seems to still use the original p2bin instead of the modified s1p2bin. This has been made even messier with the inclusion of build-time DAC driver compression and s1p2bin_plus, which effectively renders OS X totally incompatible.
- [x] Windows
- [x] OSX
- [x] Linux

**Comment by FraGag** [comment]
I've rebuilt the build tools for Linux x86-64 in f8a025b60d0742632127d98181f6aedebc91bb21.

**Comment by Clownacy** [comment]
OS X tools have been updated in 01fe86a62f0a57c8a8f6171dfa7d706a1fe9ed27 (and 48f74480cb8925cb9974129ba80765be8f932e2e).
