### ISSUE TITLE
Make HUD life icon Mapping

### ISSUE THREAD

**Issue by dawido90183** [sonicretro/s1disasm#69]
Please so i can actually edit it properly in flex2

**Comment by Clownacy** [comment]
`_maps/HUD.asm` should have the mappings for the entire HUD - score, time, and all. The trouble is that it expects the life icon to be loaded at an offset, which Flex2 might not support. It isn't hard to make your own mappings though: it's just two 3x2 sprite pieces placed side-by-side.
