### ISSUE TITLE
Document Enigma Decompression.asm

### ISSUE THREAD

**Issue by SoniEx2** [sonicretro/s1disasm#7]
[Enigma Decompression.asm](https://github.com/sonicretro/s1disasm/blob/AS/_inc/Enigma%20Decompression.asm) is currently undocumented, unlike [Kosinski Decompression.asm](https://github.com/sonicretro/s1disasm/blob/AS/_inc/Kosinski%20Decompression.asm).

The [Sonic 2 disassembly](https://github.com/sonicretro/s2disasm) has a documented Enigma decompressor, and although they have slightly different code, they both share the same code structure.

**Comment by Clownacy** [comment]
Actually, the code's identical: it's byte-for-byte the same between S1, S2, S3 and S&K.
