### ISSUE TITLE
Sonic-2-Clone-Driver-v2?? Where Is OptimiseSound variable?

### ISSUE THREAD

**Issue by MilesTailsFan2005** [sonicretro/s1disasm#70]
hey I was wondering where is this variable because its asking me to set it to 1 on the github page for it and I Cant even find it which asm file is it normally in. because without it I'm getting this

> > > sonic.asm(19):10: error #10001: error in opening file
> > > "Sonic-2-Clone-Driver-v2/Definitions.asm": No such file or directory
> > >  include "Sonic-2-Clone-Driver-v2/Definitions.asm"
> > >          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
fatal error, assembly terminated

**Comment by Clownacy** [comment]
That variable was [removed](https://github.com/sonicretro/s1disasm/commit/6fb8aa9cb43cfa09f7421674258bd36427037b4c#diff-12e96686c368ef4664489ffa94ad6e4a6299172cf1da5bc0f1543fb9f38e8f57L25) last year, so you don't need to worry about [setting it to 0](https://github.com/Clownacy/Sonic-2-Clone-Driver-v2/wiki/Installation-(Sonic-1-Git-disassembly)#note). I've updated the GitHub page to explain that this step is no longer necessary.

Your error seems to be that the file 'Definitions.asm' in the 'Sonic-2-Clone-Driver-v2' folder is missing.

**Comment by MilesTailsFan2005** [comment]
ah ok thanks for notifying me
